CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR NOT NULL,
    email   VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR NOT NULL UNIQUE,
    description   VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL,
    sum   numeric NOT NULL,
    status  VARCHAR NOT NULL,
    CONSTRAINT fk_users_orders_id FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS products_orders (
    order_id       BIGINT       NOT NULL,
    product_id      BIGINT       NOT NULL,
    PRIMARY KEY (order_id, product_id),
    CONSTRAINT orders_products_fk FOREIGN KEY (product_id)
        REFERENCES products (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT products_orders_fk FOREIGN KEY (order_id)
        REFERENCES orders (id) ON UPDATE CASCADE ON DELETE CASCADE
)